name: build and push draft

on: pull_request

jobs:
  build-draft:
    environment: beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
      - run: npm ci
      - name: deploy
        if: success()
        env:
          NODE_ENV: production
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          ARTICLE_FETCH_ENDPOINT: ${{ secrets.ARTICLE_FETCH_ENDPOINT }}
        run: npx netlify deploy --dir=dist --message ${{ github.event.pull_request.html_url }}
