name: production build from dispatch

on:
  repository_dispatch:
    types: [rebuild-website-from-airtable-hook]

jobs:
  dispatched-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - name: build
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: npm run build
      - name: deploy
        if: success()
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir=public --prod --message "${{ github.event.head_commit.message }}"
